# This is a basic workflow to help you get started with Actions

# Reference: 
  # - https://github.com/ad-m/github-push-action

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checkout yaml for code generation
      - uses: actions/checkout@v2
      - name: generate code
        run: |
            mkdir new_code
            echo $(date +%F-%T) >> new_code/date.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.LANGUAGE_REPO_TOKEN }}
          branch-suffix: timestamp 
          path: new_code
          push-to-fork: jasontsaitks/javascript-sdk