# This is a basic workflow to help you get started with Actions

# Reference: 
  # - https://github.com/ad-m/github-push-action

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        repository: jasontsaitks/javascript-sdk
        ref: refs/heads/master
        persist-credentials: false
        fetch-depth: 0
    - name: Create local changes
      run: |
        echo Hello, world!
        echo $(date +%F-%T) >> date.txt
        cat date.txt
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff
        git add .
        git commit -m "Add changes" -a
    - name: Pushes to another repository
      uses: ad-m/github-push-action@master
      with:
          branch: 'test'
          repository: jasontsaitks/javascript-sdk